-- 设置字符集（SQLite 不支持，注释掉）
-- /*!40101 SET NAMES UTF8 */;

-- 删除表 T_SDP_PARAM_CONFIG（如果存在）
DROP TABLE IF EXISTS T_SDP_PARAM_CONFIG;

-- 创建表 T_SDP_PARAM_CONFIG
CREATE TABLE T_SDP_PARAM_CONFIG (
    ID                   INTEGER PRIMARY KEY AUTOINCREMENT,
    CONFIG_NAME          VARCHAR(128) NOT NULL,
    CONFIG_VALUE         VARCHAR(256) NOT NULL,
    NODE_TYPE            INTEGER NOT NULL,
    NODE_ID              INTEGER NOT NULL,
    CONFIG_DESC          VARCHAR(1024) NOT NULL,
    UNIQUE (NODE_TYPE, NODE_ID, CONFIG_NAME) 
);

-- 删除表 T_LOG_CONFIG（如果存在）
DROP TABLE IF EXISTS T_LOG_CONFIG;

-- 创建表 T_LOG_CONFIG
CREATE TABLE T_LOG_CONFIG (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    NODE_TYPE           INTEGER NOT NULL,
    NODE_ID             INTEGER NOT NULL,
    LOG_TYPE_NAME       VARCHAR(128) NOT NULL,
    MAX_FILE_SIZE       INTEGER NOT NULL,
    MAX_BACKUP_INDEX    INTEGER NOT NULL,
    BUFFER_SIZE         INTEGER NOT NULL,
    LOG_GRADE           INTEGER NOT NULL,
    BUFFERED_IO_GRADE   INTEGER NOT NULL,
    UNIQUE (LOG_TYPE_NAME,NODE_TYPE,NODE_ID) 
);

-- 删除表 T_PLUGIN（如果存在）
DROP TABLE IF EXISTS T_PLUGIN;

-- 创建表 T_PLUGIN
CREATE TABLE T_PLUGIN (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    NODE_TYPE           INTEGER NOT NULL,
    NODE_ID             INTEGER NOT NULL,
    PLUGIN_NAME         VARCHAR(128) NOT NULL,
    PRI                 INTEGER NOT NULL DEFAULT 0,
    REMARK              VARCHAR(64),
    INUSE               INTEGER NOT NULL DEFAULT 0,
    UNIQUE (NODE_TYPE,NODE_ID, PLUGIN_NAME) 
);

-- 删除表 T_LISTEN（如果存在）
DROP TABLE IF EXISTS T_LISTEN;

-- 创建表 T_LISTEN
CREATE TABLE T_LISTEN (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    NODE_TYPE           INTEGER NOT NULL,
    NODE_ID             INTEGER NOT NULL,
    IP_ADDR             VARCHAR(32) NOT NULL,
    PORT                INTEGER NOT NULL,
    UNIQUE (NODE_TYPE,NODE_ID) 
);

-- 删除表 T_CONNECT（如果存在）
DROP TABLE IF EXISTS T_CONNECT;

-- 创建表 T_CONNECT
CREATE TABLE T_CONNECT (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    NODE_TYPE           INTEGER NOT NULL,
    NODE_ID             INTEGER NOT NULL,
    CONNECT_NODE_TYPE   INTEGER NOT NULL,
    CONNECT_NODE_ID     INTEGER NOT NULL,
    LOCAL_IP_ADDR       VARCHAR(32) NOT NULL,
    LOCAL_PORT          INTEGER NOT NULL,
    UNIQUE (NODE_TYPE,NODE_ID, CONNECT_NODE_TYPE,CONNECT_NODE_ID)
);

DROP TABLE IF EXISTS T_TLS_CONNECTION;

CREATE TABLE T_TLS_CONNECTION (
    ID                      INTEGER PRIMARY KEY AUTOINCREMENT,
    NODE_TYPE               INTEGER NOT NULL,
    NODE_ID                 INTEGER NOT NULL,
    CONNECT_NODE_TYPE       INTEGER NOT NULL,
    CONNECT_NODE_ID         INTEGER NOT NULL,
    IP_ADDR                 VARCHAR(32) NOT NULL,
    PORT                    INTEGER NOT NULL,
    VERIFY_CERT             INTEGER DEFAULT 0,
    PASSWORD                VARCHAR(32) NOT NULL,
    P12_FILE                VARCHAR(1024) NOT NULL,
    UNIQUE(NODE_TYPE, NODE_ID, CONNECT_NODE_TYPE, CONNECT_NODE_ID)
);

CREATE INDEX idx_tls_connection_id ON T_TLS_CONNECTION(ID);

DROP TABLE IF EXISTS T_TLS_LISTEN;

CREATE TABLE T_TLS_LISTEN (
    ID                      INTEGER PRIMARY KEY AUTOINCREMENT,
    NODE_TYPE               INTEGER NOT NULL,
    NODE_ID                 INTEGER NOT NULL,
    IP_ADDR                 VARCHAR(32) NOT NULL,
    PORT                    INTEGER NOT NULL,
    UNIQUE(NODE_TYPE, NODE_ID)
);

CREATE INDEX idx_tls_listen_id ON T_TLS_LISTEN(ID);
