-- 设置数据库编码为 UTF-8
PRAGMA encoding = "UTF-8";

-- ===========================
-- 表: T_DOMAIN_INFO
-- ===========================
DROP TABLE IF EXISTS T_DOMAIN_INFO;
CREATE TABLE T_DOMAIN_INFO (
   DOMAIN_ID            INTEGER PRIMARY KEY AUTOINCREMENT,
   DOMAIN_CODE          TEXT NOT NULL,
   DOMAIN_NAME          TEXT,
   DOMAIN_REMARK        TEXT,
   DOMAIN_IP            TEXT NOT NULL,
   DOMAIN_PORT          INTEGER NOT NULL,
   PARENT_DOMAIN_CODE   TEXT NOT NULL,
   IS_LOCAL_DOMAIN      INTEGER DEFAULT 0,
   DOMAIN_TYPE          INTEGER DEFAULT 0,
   LATITUDE             REAL DEFAULT 31.9713,
   LONGITUDE            REAL DEFAULT 118.7433,
   PASS_WORD            TEXT,
   DOMAIN_NAT_IP        TEXT,
   DOMAIN_MBE_PORT      INTEGER,
   DOMAIN_ACCESS_TYPE   INTEGER DEFAULT 0,
   DOMAIN_TRANSPORT_TYPE INTEGER DEFAULT 0
);

CREATE UNIQUE INDEX UQ_INDEX_CODE ON T_DOMAIN_INFO (DOMAIN_CODE);

-- ===========================
-- 表: T_SIP_LOCAL_INFO
-- ===========================
DROP TABLE IF EXISTS T_SIP_LOCAL_INFO;
CREATE TABLE T_SIP_LOCAL_INFO (
   LOCAL_DOMAINID      TEXT PRIMARY KEY,
   LOCAL_DOMAIN        TEXT NOT NULL,
   LOCAL_IP            TEXT NOT NULL,
   LOCAL_NAT_IP        TEXT NOT NULL,
   CSG_LOCAL_PORT      INTEGER NOT NULL,
   DSG_LOCAL_PORT      INTEGER NOT NULL,
   DOMAIN_LOCAL_PORT   INTEGER NOT NULL,
   PASSWORD            TEXT NOT NULL,
   PROTOCAL            INTEGER NOT NULL DEFAULT 0
);

-- ===========================
-- 表: T_CMG_LISTEN
-- ===========================
DROP TABLE IF EXISTS T_CMG_LISTEN;
CREATE TABLE T_CMG_LISTEN (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   NODE_ID             INTEGER NOT NULL,
   CONTAINER_ID        INTEGER NOT NULL,
   CMG_LISTEN_IPADDR   TEXT NOT NULL,
   CMG_LISTEN_PORT     INTEGER NOT NULL,
   CMG_NAT_IPADDR      TEXT NOT NULL,
   CMG_NAT_PORT        INTEGER NOT NULL
);

-- ===========================
-- 表: T_LOCAL_NET
-- ===========================
DROP TABLE IF EXISTS T_LOCAL_NET;
CREATE TABLE T_LOCAL_NET (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   LOCAL_IP            TEXT NOT NULL,
   LOCAL_MASK          TEXT NOT NULL
);

-- ===========================
-- 表: T_IVS_LISTEN
-- ===========================
DROP TABLE IF EXISTS T_IVS_LISTEN;
CREATE TABLE T_IVS_LISTEN (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   NODE_ID             INTEGER NOT NULL,
   CONTAINER_ID        INTEGER NOT NULL,
   CMG_LISTEN_IPADDR   TEXT NOT NULL,
   CMG_LISTEN_PORT     INTEGER NOT NULL,
   CMG_NAT_IPADDR      TEXT NOT NULL,
   CMG_NAT_PORT        INTEGER NOT NULL,
   UNIQUE (NODE_ID, CONTAINER_ID)
);

-- ===========================
-- 表: T_WS_LISTEN
-- ===========================
DROP TABLE IF EXISTS T_WS_LISTEN;
CREATE TABLE T_WS_LISTEN (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   NODE_ID             INTEGER NOT NULL,
   CONTAINER_ID        INTEGER NOT NULL,
   CMG_LISTEN_IPADDR   TEXT NOT NULL,
   CMG_NAT_IPADDR      TEXT NOT NULL,
   SINK_WS_PORT        INTEGER NOT NULL,
   SINK_WSS_PORT       INTEGER NOT NULL,
   NAT_SINK_WS_PORT    INTEGER NOT NULL,
   NAT_SINK_WSS_PORT   INTEGER NOT NULL,
   SOURCE_WS_PORT      INTEGER NOT NULL,
   SOURCE_WSS_PORT     INTEGER NOT NULL,
   NAT_SOURCE_WS_PORT  INTEGER NOT NULL,
   NAT_SOURCE_WSS_PORT INTEGER NOT NULL,
   UNIQUE (NODE_ID, CONTAINER_ID)
);

-- ===========================
-- 表: T_TURN_CONFIG
-- ===========================
DROP TABLE IF EXISTS T_TURN_CONFIG;
CREATE TABLE T_TURN_CONFIG (
   SERVER_IP           TEXT PRIMARY KEY,
   SERVER_PORT         INTEGER NOT NULL,
   UNIQUE (SERVER_IP)
);

-- ===========================
-- 表: T_FORWARDING_CONFIG
-- ===========================
DROP TABLE IF EXISTS T_FORWARDING_CONFIG;
CREATE TABLE T_FORWARDING_CONFIG (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   NODE_ID             INTEGER NOT NULL,
   MTN_ID              INTEGER NOT NULL,
   MTN_IP              TEXT NOT NULL,
   MTN_PORT            INTEGER NOT NULL,
   MTN_NAT_IP          TEXT NOT NULL,
   MTN_NAT_PORT        INTEGER NOT NULL,
   MTN_VIDEO_PORT      INTEGER DEFAULT 9500,
   MTN_VIDEO_NAT_PORT  INTEGER DEFAULT 9500,
   MTN_AUDIO_PORT      INTEGER DEFAULT 9501,
   MTN_AUDIO_NAT_PORT  INTEGER DEFAULT 9501,
   NODE_NAME           TEXT
);

-- ===========================
-- 表: T_MTN_NAT_CONFIG
-- ===========================
DROP TABLE IF EXISTS T_MTN_NAT_CONFIG;
CREATE TABLE T_MTN_NAT_CONFIG (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   NODE_ID             INTEGER NOT NULL,
   MTN_ID              INTEGER NOT NULL,
   MTN_IP              TEXT NOT NULL,
   MTN_PORT            INTEGER NOT NULL,
   MTN_NAT_IP          TEXT NOT NULL,
   MTN_NAT_PORT        INTEGER NOT NULL,
   UNIQUE (NODE_ID, MTN_ID)
);

-- ===========================
-- 表: T_CMF_RECORD_DEVICE
-- ===========================
DROP TABLE IF EXISTS T_CMF_RECORD_DEVICE;
CREATE TABLE T_CMF_RECORD_DEVICE (
   USER_ID             TEXT NOT NULL,
   DOMAIN_CODE         TEXT NOT NULL,
   USER_NAME           TEXT,
   STATE               INTEGER DEFAULT 0,
   MN_ID               INTEGER DEFAULT -1,
   SERVICE_ID          INTEGER DEFAULT -1,
   CHANNEL_FLAG        INTEGER DEFAULT 1,
   FOCUS_CHANNEL_ID    INTEGER DEFAULT 1,
   MN_PLAY_ID          INTEGER DEFAULT -1,
   SERVICE_PLAY_ID     INTEGER DEFAULT -1,
   UNIQUE(USER_ID, DOMAIN_CODE)
);

-- ===========================
-- 表: T_SIP_AUDIO_CODEC
-- ===========================
DROP TABLE IF EXISTS T_SIP_AUDIO_CODEC;
CREATE TABLE T_SIP_AUDIO_CODEC (
   ID                  INTEGER PRIMARY KEY,
   AUDIO_FORMAT        TEXT,
   SAMPLING_RATE       INTEGER NOT NULL,
   SOUNDTRACK          INTEGER NOT NULL,
   PAYLOAD_TYPE        INTEGER NOT NULL
);

-- ===========================
-- 表: T_SIP_VIDEO_CODEC
-- ===========================
DROP TABLE IF EXISTS T_SIP_VIDEO_CODEC;
CREATE TABLE T_SIP_VIDEO_CODEC (
   ID                  INTEGER PRIMARY KEY,
   VIDEO_FORMAT        TEXT,
   SAMPLING_RATE       INTEGER NOT NULL,
   PAYLOAD_TYPE        INTEGER NOT NULL
);

-- ===========================
-- 表: T_CMF_SEQ
-- ===========================
DROP TABLE IF EXISTS T_CMF_SEQ;
CREATE TABLE T_CMF_SEQ (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   NN                  INTEGER DEFAULT 0
);

-- ===========================
-- 表: T_PUNCH_CLIENT_CONFIG
-- ===========================
DROP TABLE IF EXISTS T_PUNCH_CLIENT_CONFIG;
CREATE TABLE T_PUNCH_CLIENT_CONFIG (
   SIE_IP              TEXT PRIMARY KEY,
   PUNCH_IP            TEXT NOT NULL,
   PUNCH_PORT          INTEGER NOT NULL,
   UNIQUE(SIE_IP)
);

-- ===========================
-- 表: T_CONVERT_ADDR_CONFIG
-- ===========================
DROP TABLE IF EXISTS T_CONVERT_ADDR_CONFIG;
CREATE TABLE T_CONVERT_ADDR_CONFIG (
   ORIGIN_IP           TEXT PRIMARY KEY,
   TARGET_IP           TEXT NOT NULL,
   UNIQUE(ORIGIN_IP)
);

-- ===========================
-- 表: T_SIP_TRUNK
-- ===========================
DROP TABLE IF EXISTS T_SIP_TRUNK;
CREATE TABLE T_SIP_TRUNK (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   SIP_ADDR            TEXT NOT NULL,
   SIP_PORT            INTEGER DEFAULT 5060,
   SHORT_NUM           TEXT,
   PHONE_NUM           TEXT,
   HB_INTERVAL         INTEGER DEFAULT 0,
   UNIQUE(SIP_ADDR, SIP_PORT)
);

-- ===========================
-- 表: T_SIP_ENCRYPT
-- ===========================
DROP TABLE IF EXISTS T_SIP_ENCRYPT;
CREATE TABLE T_SIP_ENCRYPT (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   NODE_ID             INTEGER NOT NULL,
   CONTAINER_ID        INTEGER NOT NULL,
   KEY_FILE            TEXT NOT NULL,
   DEV_PATH            TEXT NOT NULL,
   ENCRYPT_TYPE        INTEGER DEFAULT -1,
   KEY_PASS            TEXT NOT NULL,
   DEV_ID              TEXT,
   USER_ID             TEXT
);

-- ===========================
-- 表: T_SCM_AGENT_INFO
-- ===========================
DROP TABLE IF EXISTS T_SCM_AGENT_INFO;
CREATE TABLE T_SCM_AGENT_INFO (
   ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
   AGENT_IP            TEXT NOT NULL,
   NEGOTIATTE_PORT     INTEGER DEFAULT 0,
   NODE_COMMUNICATION_PORT INTEGER DEFAULT 0,
   DATA_PORT           INTEGER DEFAULT 0,
   CONTACT_PORT        INTEGER DEFAULT 0,
   NODE_ID             INTEGER NOT NULL,
   CONTAINER_ID        INTEGER NOT NULL
);

-- ===========================
-- 表: T_SIP_RFC_LOCAL_INFO
-- ===========================
DROP TABLE IF EXISTS T_SIP_RFC_LOCAL_INFO;
CREATE TABLE T_SIP_RFC_LOCAL_INFO (
   LOCAL_DOMAINID      TEXT NOT NULL,
   LOCAL_DOMAIN        TEXT NOT NULL,
   LOCAL_IP            TEXT NOT NULL,
   DOMAIN_LOCAL_PORT   INTEGER NOT NULL,
   PASSWORD            TEXT NOT NULL,
   PRIMARY KEY (LOCAL_DOMAINID)
);

-- ===========================
-- 表: T_MTN_LOAD_CONFIG
-- ===========================
DROP TABLE IF EXISTS T_MTN_LOAD_CONFIG;
CREATE TABLE T_MTN_LOAD_CONFIG (
    NODE_ID             INTEGER NOT NULL,
    MTN_MAX_CAPTURE_BAND INTEGER NOT NULL,
    MTN_MAX_PLAY_BAND   INTEGER NOT NULL,
    MTN_PERCENT         INTEGER NOT NULL,
    PRIMARY KEY (NODE_ID)
);

-- ===========================
-- 表: T_PLUGIN_DETAIL
-- ===========================
DROP TABLE IF EXISTS T_PLUGIN_DETAIL;
CREATE TABLE T_PLUGIN_DETAIL (
    PLUGIN_ID      INTEGER NOT NULL,
    PLUGIN_NAME    TEXT NOT NULL,
    PRIMARY KEY (PLUGIN_ID, PLUGIN_NAME)
);
