/*==============================================================*/
/* DBMS NAME:      MYSQL 5.0                                    */
/* CREATED ON:     2013-9-17 18:09:15                           */
/*==============================================================*/
/*!40101 SET NAMES UTF8 */;

#基础插件

INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'server_nat_gateway',0,'IVS协议反向网关服务端',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'client_nat_gateway',0,'IVS协议反向网关客户端',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'hyp_gateway',0,'hyp信令协议服务网关',1);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'mbe_client_http_gateway',0,'HTTP客户端网关',1);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'ws_gateway',0,'websocket网关',1);

INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'media_transfers_node',0,'媒体转发内核模块',1);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'ivs_media_sink',1,'IVS正向协议媒体访问',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'ivs_reverse_sink',1,'IVS反向协议媒体访问',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'rtsp_media_sink',1,'rtsp协议媒体访问',1);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'ivs_reverse_source',1,'IVS反向媒体接入',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'rtmp_source',1,'RTMP协议媒体接入',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'rtsp_udp_source',1,'RTSP UDP媒体接入',1);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'rtsp_tcp_source',1,'RTSP TCP设备媒体接入',1);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'sip_media_sink',1,'28181上级域媒体访问',0);

#SIP设备接入服务（IP话机）
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'sipex_source',1,'sip UDP媒体接入',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'service_sip_gateway',0,'SIP服务网关',0);

#加解密相关
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'cm_service',0,'中心密码机对接网关',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'kdc_agent',0,'加密KDC代理',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'lkdc_https_agent',0,'加密LKDC代理网关',0);
INSERT INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'scm_service',0,'软件加密插件',0);


INSERT INTO `T_PLUGIN_DETAIL` VALUES ('6', 'sip_media_sink');



#日志配置表
INSERT INTO T_LOG_CONFIG(NODE_TYPE, NODE_ID, LOG_TYPE_NAME, MAX_FILE_SIZE, MAX_BACKUP_INDEX, BUFFER_SIZE, LOG_GRADE, BUFFERED_IO_GRADE) VALUES(0, 0, 'RUN', 10, 10, 1, 1, 1);
INSERT INTO T_LOG_CONFIG(NODE_TYPE, NODE_ID, LOG_TYPE_NAME, MAX_FILE_SIZE, MAX_BACKUP_INDEX, BUFFER_SIZE, LOG_GRADE, BUFFERED_IO_GRADE) VALUES(0, 0, 'INTERFACE', 10, 10, 1, 1, 1);
INSERT INTO T_LOG_CONFIG(NODE_TYPE, NODE_ID, LOG_TYPE_NAME, MAX_FILE_SIZE, MAX_BACKUP_INDEX, BUFFER_SIZE, LOG_GRADE, BUFFERED_IO_GRADE) VALUES(0, 0, 'STATISTIC', 10, 10, 1, 1, 1);

#进程监听工程数据

INSERT INTO T_LISTEN(NODE_TYPE, NODE_ID, IP_ADDR, PORT) VALUES(999, 1, '192.168.1.108', 9990);


#连接表工程数据

INSERT INTO T_CONNECT(NODE_TYPE, NODE_ID, CONNECT_NODE_TYPE, CONNECT_NODE_ID, LOCAL_IP_ADDR, LOCAL_PORT) VALUES(999, 1, 666, 1, '127.0.0.1', -1);
INSERT INTO T_CONNECT(NODE_TYPE, NODE_ID, CONNECT_NODE_TYPE, CONNECT_NODE_ID, LOCAL_IP_ADDR, LOCAL_PORT) VALUES(888, 1, 666, 1, '127.0.0.1', -1);
INSERT INTO T_CONNECT(NODE_TYPE, NODE_ID, CONNECT_NODE_TYPE, CONNECT_NODE_ID, LOCAL_IP_ADDR, LOCAL_PORT) VALUES(888, 1, 999, 1, '127.0.0.1', -1);


#sdp配置表
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SDP_INNER_CORRESPOND_SERVICE_CONTAINER_NUM', '1', 0, 0,'内部线程数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SDP_EXTERNAL_CORRESPOND_SERVICE_CONTAINER_NUM', '4', 0, 0,'外部线程数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('LOG_CREATE_LOG_PERIORD_SWITCH', '1', 0, 0,'日志保留开关');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('LOG_CREATE_LOG_PERIORD', '1', 0, 0,'日志保留天数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('LOG_ARCHIVE_SWITCH', '0', 0, 0,'日志归档标识');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('HEART_BEAT_INTERVAL', '10', 0, 0,'心跳超时间隔');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('HEART_BEAT_TIMEOUT_COUNT', '10', 0, 0,'心跳超时次数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DCG_PROBE_MATCH_TIME_OUT', '5', 999, 0,'probe超时时间');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DCG_GET_DEVICE_LIST_TIME_OUT', '30', 999, 0,'发现设备超时时间');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_MEDIA_MIN_UDP_PORT', '10000', 888, 0,'视频UDP最小端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_MEDIA_MAX_UDP_PORT', '30000', 888, 0,'视频UDP最大端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_AUDIO_MIN_UDP_PORT', '0', 888, 0,'音频UDP最小端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_AUDIO_MAX_UDP_PORT', '0', 888, 0,'音频UDP最大端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SERVER_NETCARD_IP', '192.168.1.106', 0, 0,'内网网卡IP');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('CIG_LISTEN_IPADDR', '192.168.1.106', 0, 0,'网关监听地址');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('CIG_LISTEN_PORT', '9000', 0, 0,'ivs网关监听端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('CHJG_LISTEN_PORT', '9200', 0, 0,'http+json网关监听端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('ESG_LISTEN_PORT', '8888', 0, 0,'告警网关监听端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MAX_KEEP_ALIVE_DCG_NUM', '1', 0, 0,'保活网关节点个数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('ROUT_TYPE', '1', 0, 0,'多域路由方式,0:多级转发，1:点对点，2:路由表');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MSS_THREHOLD', '100', 0, 0,'存储队列告警阈值');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DEFAULT_DOMAIN_TRANSFER_PROTOCOL', '1', 0, 0,'多域码流传输方式(默认为tcp)');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DEFAULT_UDP_SLEEP_FLAG', '0', 888, 0,'UDP多并发睡眠标识');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MTN_THREAD_NUM', '1', 0, 0,'媒体转发线程数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('TDS_THREAD_NUM', '1', 0, 0,'设备状态检测服务线程数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('TDS_TIMEOUT', '5', 0, 0,'设备状态检测超时时长');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('TDS_CYCLE_TIMEOUT', '900', 0, 0,'所有设备状态检测大周期超时时长');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('TDS_DEVICE_NUM_PERTIME', '100', 0, 0,'每个周期检测设备数量');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('TDS_DETECT_CHANNEL_28181', '0', 0, 0,'28181设备是否检测到通道在线');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SCG_LISTEN_PORT', '9997', 0, 0,'部署配置网关监听端口');;
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('HYP_LISTEN_PORT', '9001', 0, 0,'音视频SDK接入端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('HYPS_LISTEN_PORT', '9003', 0, 0,'音视频SDK tls接入端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('NOTIFY_RECORD_DOMAINCODE', '', 0, 0,'录像成功通知域编码');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('NOTIFY_RECORD_URL', '', 0, 0,'录像成功通知URL');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MAX_USER_NUM_PER_MEETING', '50', 0, 0,'单次会议中参与人数上限');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('CAPTURE_USER_DEVICE', '0', 0, 0,'是否添加终端采集设备 0：否，1：是');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MAX_PICUSER_NUM_PER_MEETING', '6', 0, 0,'单次会议中合成画面人数上限');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MAX_PHONE_TALKBACK_ACCEPT_NUM', '4', 0, 0,'手机一对多对讲，接听个数限制');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MAX_PC_TALKBACK_ACCEPT_NUM', '16', 0, 0,'PC一对多对讲，接听个数限制');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MBE_USER_TIMEOUT_SECONDS', '1800', 0, 0,'MBE用户session超时时间');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SIP_CLIENT_VIDEO_RESOLUTION', '0', 0, 0,'SIP客户端视频分辨率，0：标清，1：高清');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('PREDETERMINE_MEETING_WAIT_TIMEOUT', '1800', 0, 0,'预约会议第一次无人加入超时时间（单位：秒）');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('ARCHIVE_PRESET_SPACE', '10', 0, 0,'归档预置空间（G为单位）');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('FILE_SERVER_PATH', '/home/ecs/apache-tomcat-7.0.42/webapps/ECSFileServer/', 0, 0,'文件服务器路径');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('ENABLE_SIP_NACK', '0', 0, 0,'科达平台丢包重传开关');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CONVERT_IMAGE_TYPE', 'jpeg', 0, 0, '转换文件类型(jpeg, svg, png)');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MBE_USER_NOTIFY_SCOPE', '1', 0, 0, '用户通知范围，0：通知好友，1：通知本域，2：通知本域和上级域，3：通知所有域');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SSA_LISTEN_PORT', '5080', 0, 0,'西门子告警网关监听端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MAX_TRUNK_CHANNEL_NUM', '100', 0, 0,'集群对讲个数限制');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MAX_USER_NUM_IN_TRUNK_CHANNEL', '200', 0, 0,'单个集群对讲人员限制');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('VIDEO_SCREENSHOT_PATH', '/home', 0, 0,'视频截图存放路径');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MESH_IP_ADDR', '', 0, 0,'自组网设备获取IP地址');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('bIfSupportPTP', '0', 0, 0,'是否支持PTP 0：不支持 1：支持');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('URL_SCREENSHOT_INTERVAL', '60', 0, 0,'相同URL返回上次截图时间间隔');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SERIAL_PORT_NAME', '/dev/ttyS0', 0, 0,'串口名称');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SERIAL_SCREEN_TITLE', 'HyperMesh', 0, 0,'串口屏幕标题');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('TDS_AUTO', '0', 0, 0,'设备在线是否自动检测 0：否 1：是');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_SIP_SOURCE_MIN_TCP_PORT', '20000', 0, 0,'SIP SOURCE最小TCP端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_SIP_SOURCE_MAX_TCP_PORT', '24999', 0, 0,'SIP SOURCE最大TCP端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_SIP_SINK_MIN_TCP_PORT', '25000', 0, 0,'SIP SINK最小TCP端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_SIP_SINK_MAX_TCP_PORT', '29999', 0, 0,'SIP SINK最大TCP端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SIP_SOURCE_TCP_CONNECT_TYPE', '0', 0, 0,'SIP SOURCE TCP连接方式，0：passive, 1: active');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_SIPEX_MIN_TCP_PORT', '30000', 0, 0,'SIP EX最小TCP端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('MTN_SIPEX_MAX_TCP_PORT', '34999', 0, 0,'SIP EX最大TCP端口号');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SIPEX_TCP_CONNECT_TYPE', 'active', 0, 0,'SIPEX TCP连接方式，被动连接：passive, 主动连接: active');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SIPEX_TS_TYPE_CONFIG', '0', 0, 0,'SIPEX TCP连接方式，0：udp, 1: tcp');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('TEST_28181_SWITCH', '0', 0, 0,'28181测试代码开关，0：关, 1: 开');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('28181_DOWNLOAD_FLAG', '0', 0, 0,'28181下载标志位，0：关, 1: 开');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DEFAULT_AUTO_SUBSCRIBE_CATALOG', '1', 0, 0,'自动目录订阅');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DEFAULT_AUTO_SUBSCRIBE_MOBILE_POSTION', '0', 0, 0,'自动订阅移动位置');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DEFAULT_MOBILE_POSTION_NOTIFY_INTERVAL', '10', 0, 0,'移动位置上报间隔');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('DEFAULT_28181_STREAM_TS_TYPE', '0', 0, 0,'28181码流传输类型，0：udp, 1: tcp');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('COUNT_MEETING_PERSON_NUM_FOR_AUTO_TEST', '0', 0, 0,'自动化测试设备也算为参会人');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SAT_LISTEN_PORT', '20000', '999', '0', '卫星GPS');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('FILE_SERVER_IP', '', '0', '0', '文件服务器地址');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('FILE_SERVER_PORT', '', '0', '0', '文件服务器端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('WS_GW_LISTEN', '12000', '999', '0', 'WebSocket网关端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('WSS_GW_LISTEN', '13000', '999', '0', 'WebSockets网关端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CMF_AUDIO_MAX_RATE', '64000', '0', '0', '音频最大速率');

INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('ONVIF_SERVER_PORT', '7000', 0, 0,'onivf服务端端口');

INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CMF_VAD_DETECT', '0', 0, 0,'是否选择声音能量最大的几路发送');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CMF_MAX_VAD_NUM', '5', 0, 0,'能量最大路数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CMF_VAD_DETECT_LOG', '0', 0, 0,'是否打开声音检测日志');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SERVER_CLUSTER_TRANSPORT_PROTOCOL', 1, 0, 0,'服务器集群传输协议(默认为TCP)');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SIP_PARENT_CONFIG', '0', 999, 0, 'sip的parent配置');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MBE_MEETING_KEEP_ALIVE_TIMEOUT_SECONDS', '120', 0, 0, '会议保活时长限制');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CMF_SERVER_PUNCH_CONFIG', '0', 0, 0, '服务器是否需要打洞配置（端口一一映射的可以配置成不需要），1需要，0不需要');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('DOMAIN_JSON_SERVER_IP', '0', 0, 0, '跨域JSON消息透传网关IP');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('DOMAIN_JSON_SERVER_PORT', '0', 0, 0, '跨域JSON消息透传网关PORT');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('RTMP_SINK_PORT', 1936, 0, 0,'rtmp 播放端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SIP_SOURCE_MAX_SEND_BUFFER_SIZE', 10, 0, 0,'sip缓存后一次发送rtp包最大个数,配置为0，ps和rtp包不缓存');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CMF_KCP_SQ_BASE_RP_NUM', 300, 0, 0,'KCP拥塞队列基数');

INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('DISPATCH_CENTER_NODE', 666, 0, 0,'调度中心节点类型');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('DISPATCH_CENTER_SERVICE', 2345, 0, 0,'调度中心服务类型');

INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MAX_MEETING_NUMBER', '-1', '0', '0', '会议最大数目');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MAX_DAYS_OF_OFFLINE_MSG_IN_DB', '30', '0', '0', '离线消息保留最大天数，默认30天');

INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SRS_PORT', '1935', 0, 0, 'SRS监听端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SRS_HOST', '127.0.0.1', 0, 0, 'SRS服务器地址');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('USE_NATIVE_RTMP', 1, 0, 0, '是否启用内置RTMP SERVER');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('IS_SERVER', 1, 0, 0, '是否是rtmp收流');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('CLIENT_CATALOG_DEVICE_COUNT_PER_MSG', 1, 0, 0, '28181每包同步的通道数');

INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('STATISTICS_RTSP_BANDS', 1, 0, 0, '是否统计RTPS播放带宽控制');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('4K_MODE_CONFIG', 0, 0, 0, '是否是4K模式，0否，1是');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('5G_NODE_UDP_NON_BLOCK_MODE', 1, 0, 0, '5G网关udp是否是非阻塞模式 1是，0否');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MBE_MEETING_MAX_MICROPHONE_ON_NUM', 50, 0, 0,'会议最大允许同时说话人数');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('RECORD_RAW_AND_MP4', 1, 0, 0, '是否裸盘和Mp4一起录制，1是，0否');

INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('DATA_MIGRATION_LISTEN_PORT', '11221', 0, 0,'数据迁移服务器监听端口');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('SIP_TRUNK_ENABLE', 0, 0, 0, '是否启动SIP_TRUNK，1是，0否');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MESSAGE_PUSH_TITLE', '密信', 0, 0,'离线消息推送消息标题');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('HYP_MUTUAL_AUTH', 0, 0, 0,'HYP协议双向认证');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('HYP_TLS_KEY_PWD', '', 0, 0,'HYP协议tls私钥密码');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('MAX_MEETING_DURATION', '-1', 0, 0,'会议最大时长');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('REPORT_DELAY_DURATION', '5', 0, 0,'延时持续时间(秒)');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('REPORT_DELAY_RTT', '300', 0, 0,'需要上报的延迟时间(毫秒)');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('NOTIFY_MEETING_END_TIME', '600,300', 0, 0,'会议结束通知(秒)');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('USER_GROUP_PERMISSION_ENABLE', '0', 0, 0,'用户组权限过滤开关，0：不过滤；1-过滤');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('SIP_PROBE_TIMEOUT_SEC', '20', 0, 0,'国标同步等待应答超时时间，单位秒');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES('CHANNEL_CNT_INCLUDE_LOWER_DOMAIN', '0', 0, 0,'统计分组通道数量是否包含下级域的通道，0：不包含；1-包含');
INSERT INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('IS_PHONE_GATEWAY', '0', 0, 0,'是否是电话网关');

#媒体网关地址表
INSERT INTO T_CMG_LISTEN(NODE_ID, CONTAINER_ID, CMG_LISTEN_IPADDR, CMG_LISTEN_PORT, CMG_NAT_IPADDR, CMG_NAT_PORT) VALUES('1','1','192.168.1.106','1554','192.168.1.106','1554');
INSERT INTO T_IVS_LISTEN(NODE_ID, CONTAINER_ID, CMG_LISTEN_IPADDR, CMG_LISTEN_PORT, CMG_NAT_IPADDR, CMG_NAT_PORT) VALUES('1','1','192.168.1.106','9062','192.168.1.106','9062');


#sip表
INSERT INTO T_SIP_RFC_LOCAL_INFO(LOCAL_DOMAINID, LOCAL_DOMAIN, LOCAL_IP, DOMAIN_LOCAL_PORT, PASSWORD) VALUES('1','1','192.168.1.106',5060,'123456');

#域工程数据
INSERT INTO T_DOMAIN_INFO (DOMAIN_CODE,DOMAIN_NAME,DOMAIN_REMARK,DOMAIN_IP,DOMAIN_PORT,PARENT_DOMAIN_CODE,IS_LOCAL_DOMAIN,DOMAIN_NAT_IP,DOMAIN_MBE_PORT) VALUES('3401000000','怀业流媒体平台','怀业流媒体平台','192.168.129.55','9000','3401000000','1','192.168.129.55','3478');

##########################################################################################################################################################################################


-- ----------------------------
-- Records of t_disk_full_policy
-- ----------------------------

INSERT INTO `T_TURN_CONFIG` VALUES ('200.100.1.158', '3478');
INSERT INTO `T_FORWARDING_CONFIG` VALUES ('1','1', '1', '192.168.2.224', '9012', '192.168.2.224', '9012', '9500', '9500', '9501', '9501', '');
INSERT INTO `T_MTN_NAT_CONFIG` VALUES ('1','1', '1', '192.168.2.224', '9042', '192.168.2.224', '9042');

-- ----------------------------
-- Distributed node ID bandwidth
-- ----------------------------
INSERT INTO `T_MTN_LOAD_CONFIG` VALUES ('1', '1000', '1000', '90');

-- ----------------------------
-- Records of t_sip_audio_endecode
-- ----------------------------
INSERT INTO `T_SIP_AUDIO_CODEC` VALUES ('1', 'pcma', '8000', '1', '8');

-- ----------------------------
-- Records of t_sip_video_endecode
-- ----------------------------
INSERT INTO `T_SIP_VIDEO_CODEC` VALUES ('1', 'h264', '90000', '96');
