REPLACE INTO T_SDP_PARAM_CONFIG(CONFIG_NAME, CONFIG_VALUE, NODE_TYPE, NODE_ID,CONFIG_DESC) VALUES ('IS_PHONE_GATEWAY', '1', 0, 0,'是否是电话网关');
REPLACE INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'hyp_gateway',0,'hyp信令协议服务网关',0);
REPLACE INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'mbe_client_http_gateway',0,'HTTP客户端网关',0);
REPLACE INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(999, 0, 'ws_gateway',0,'websocket网关',0);
REPLACE INTO T_PLUGIN(NODE_TYPE, NODE_ID, PLUGIN_NAME,PRI,REMARK,INUSE) VALUES(888, 0, 'rtsp_udp_source',1,'RTSP UDP媒体接入',0);
